import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import type { CSSProperties } from 'react'
import type { Attachment, Note, Notebook } from '../../types'
import { activeNotes, DEFAULT_NOTEBOOK_ID, nextActiveOrder, notesInNotebook, removeNotebook, reorderActiveNotes, trashNote } from '../../domain/notes'
import { MarkdownEditorAdapter } from '../../components/markdown/MarkdownEditorAdapter'
import { MarkdownRenderer } from '../../components/markdown/MarkdownRenderer'

type Props={notes:Note[];notebooks:Notebook[];setNotes:React.Dispatch<React.SetStateAction<Note[]>>;setNotebooks:React.Dispatch<React.SetStateAction<Notebook[]>>;requestedNoteId?:string|null;onRequestedNoteHandled?:()=>void;onAddImages:(noteId:string,files:FileList|null)=>Promise<void>;putAttachmentBlob:(key:string,blob:Blob)=>Promise<void>;getAttachmentBlob:(key:string)=>Promise<Blob|undefined>;onPreviewImage:(attachment:Attachment)=>void}
export function NotesPage({notes,notebooks,setNotes,setNotebooks,requestedNoteId,onRequestedNoteHandled,onAddImages,putAttachmentBlob,getAttachmentBlob,onPreviewImage}:Props){
 const [notebookOpen,setNotebookOpen]=useState(false), [selectedNotebook,setSelectedNotebook]=useState<string|null>(null), [editingId,setEditingId]=useState<string|null>(null), [mobileMode,setMobileMode]=useState<'edit'|'preview'>('edit')
 const [recording,setRecording]=useState(false), [recordingSeconds,setRecordingSeconds]=useState(0), [mediaRecorder,setMediaRecorder]=useState<MediaRecorder|null>(null)
 const active=useMemo(()=>activeNotes(notes),[notes]); const shown=selectedNotebook?notesInNotebook(notes,selectedNotebook):active
 const editing=notes.find(n=>n.id===editingId&&!n.trashedAt)
 useEffect(()=>{if(!requestedNoteId)return;const target=notes.find(n=>n.id===requestedNoteId&&!n.trashedAt);if(target){setEditingId(target.id);setSelectedNotebook(target.notebookId)}onRequestedNoteHandled?.()},[requestedNoteId,notes,onRequestedNoteHandled])
 const previewRef=useRef<HTMLDivElement>(null)
 const [mobileViewport,setMobileViewport]=useState<{top:number;height:number}|null>(null)
 useEffect(()=>{
  if(!editing)return
  const viewport=window.visualViewport
  const update=()=>setMobileViewport(viewport?{top:viewport.offsetTop,height:viewport.height}:null)
  update()
  viewport?.addEventListener('resize',update)
  viewport?.addEventListener('scroll',update)
  const previousOverflow=document.documentElement.style.overflow
  const previousBodyOverflow=document.body.style.overflow
  document.documentElement.style.overflow='hidden'
  document.body.style.overflow='hidden'
  return ()=>{
   viewport?.removeEventListener('resize',update)
   viewport?.removeEventListener('scroll',update)
   document.documentElement.style.overflow=previousOverflow
   document.body.style.overflow=previousBodyOverflow
  }
 },[editingId])
 const editorViewportStyle=mobileViewport?({'--note-vv-top':`${mobileViewport.top}px`,'--note-vv-height':`${mobileViewport.height}px`} as CSSProperties):undefined
 const syncPreviewScroll=useCallback((ratio:number)=>{
  const preview=previewRef.current
  if(!preview)return
  const max=preview.scrollHeight-preview.clientHeight
  preview.scrollTop=max>0?ratio*max:0
 },[])
 const createNote=()=>{const now=new Date().toISOString(), id=crypto.randomUUID(); const notebookId=selectedNotebook??DEFAULT_NOTEBOOK_ID; setNotes(x=>[...x,{id,notebookId,title:'未命名笔记',content:'',active:!selectedNotebook,activeOrder:!selectedNotebook?nextActiveOrder(x):undefined,createdAt:now,updatedAt:now,tagIds:[],attachments:[]}]);setEditingId(id)}
 const patch=(patch:Partial<Note>)=>setNotes(x=>x.map(n=>n.id===editingId?{...n,...patch,updatedAt:new Date().toISOString()}:n))
 const toggleActive=(n:Note)=>setNotes(x=>x.map(row=>row.id===n.id?{...row,active:!row.active,activeOrder:row.active?undefined:nextActiveOrder(x),updatedAt:new Date().toISOString()}:row))
 const move=(id:string,delta:number)=>{const ids=active.map(n=>n.id), i=ids.indexOf(id), j=i+delta;if(i<0||j<0||j>=ids.length)return;[ids[i],ids[j]]=[ids[j],ids[i]];setNotes(x=>reorderActiveNotes(x,ids,new Date().toISOString()))}
 const addNotebook=()=>{const name=window.prompt('笔记本名称')?.trim();if(!name)return;const now=new Date().toISOString();setNotebooks(x=>[...x,{id:crypto.randomUUID(),name,order:x.length,createdAt:now,updatedAt:now}])}
 const deleteNote=(note:Note)=>{if(!window.confirm(`删除「${note.title}」？笔记将移入回收站。`))return;const now=new Date().toISOString();setNotes(x=>x.map(row=>row.id===note.id?trashNote(row,now):row));setEditingId(null)}
 const deleteNotebook=(book:Notebook)=>{if(book.id===DEFAULT_NOTEBOOK_ID)return;if(!window.confirm(`删除「${book.name}」？其中的笔记将移动到「默认」。`))return;const now=new Date().toISOString();setNotes(x=>removeNotebook(x,book.id,now));setNotebooks(x=>x.filter(b=>b.id!==book.id));if(selectedNotebook===book.id)setSelectedNotebook(DEFAULT_NOTEBOOK_ID)}
 const removeAttachment=(attachment:Attachment)=>{const now=new Date().toISOString();setNotes(rows=>rows.map(note=>{if(note.id!==editingId)return note;const tombstones={...(note.attachmentLinkTombstones??{}),[attachment.storageKey]:now};return {...note,attachments:(note.attachments??[]).filter(item=>item.id!==attachment.id),attachmentLinkTombstones:tombstones,updatedAt:now}}))}
 const startRecording=async()=>{if(!editing||editing.attachments?.some(a=>a.type==='audio')||recording)return;try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});const preferred=['audio/webm;codecs=opus','audio/webm','audio/mp4'];const mimeType=preferred.find(type=>typeof MediaRecorder!=='undefined'&&MediaRecorder.isTypeSupported(type));const recorder=mimeType?new MediaRecorder(stream,{mimeType}):new MediaRecorder(stream);const chunks:BlobPart[]=[];const startedAt=Date.now();recorder.ondataavailable=event=>{if(event.data&&event.data.size>0)chunks.push(event.data)};recorder.onerror=()=>{stream.getTracks().forEach(track=>track.stop());setRecording(false);setMediaRecorder(null);setRecordingSeconds(0);window.alert('录音失败，请重新录制。')};recorder.onstop=async()=>{stream.getTracks().forEach(track=>track.stop());const duration=Math.max(0,Math.round((Date.now()-startedAt)/1000));const blob=new Blob(chunks,{type:recorder.mimeType||mimeType||'audio/webm'});setRecording(false);setMediaRecorder(null);setRecordingSeconds(0);if(duration<1||blob.size<512){window.alert('录音内容为空或时间太短，没有保存。请重新录制。');return}const id=crypto.randomUUID(),storageKey=`attachment:${id}`,createdAt=new Date().toISOString(),extension=blob.type.includes('mp4')?'m4a':'webm';await putAttachmentBlob(storageKey,blob);setNotes(rows=>rows.map(note=>note.id===editing.id?{...note,attachments:[...(note.attachments??[]).filter(a=>a.type!=='audio'),{id,type:'audio',filename:`录音-${new Date().toLocaleString()}.${extension}`,mimeType:blob.type,size:blob.size,storageKey,duration,createdAt}],attachmentLinkTombstones:Object.fromEntries(Object.entries(note.attachmentLinkTombstones??{}).filter(([key])=>key!==storageKey)),updatedAt:createdAt}:note))};recorder.start(1000);setRecordingSeconds(0);setMediaRecorder(recorder);setRecording(true)}catch(error){console.error('Failed to start note recording',error);window.alert('无法开始录音，请检查麦克风权限。')}}
 const stopRecording=()=>{if(mediaRecorder&&mediaRecorder.state!=='inactive'){try{mediaRecorder.requestData()}catch{}window.setTimeout(()=>{if(mediaRecorder.state!=='inactive')mediaRecorder.stop()},80)}}
 useEffect(()=>{if(!recording)return;const timer=window.setInterval(()=>setRecordingSeconds(value=>{if(value>=1799){stopRecording();return 1800}return value+1}),1000);return()=>window.clearInterval(timer)},[recording,mediaRecorder])
 return <section className="notes-page">
  <div className="page-heading notes-heading"><div><span className="eyebrow">NOTES</span><h2>{selectedNotebook?notebooks.find(b=>b.id===selectedNotebook)?.name:'笔记'}</h2></div><div className="notes-actions"><button onClick={()=>setNotebookOpen(true)}>笔记本</button><button className="primary" onClick={createNote}>＋ 新建</button></div></div>
  {!selectedNotebook&&<p className="notes-subtitle">已激活笔记 · 当前工作集</p>}
  <div className="note-list">{shown.length?shown.map((n,index)=><article key={n.id} className="note-row" onClick={()=>setEditingId(n.id)}><div><strong>{n.title}</strong><p>{n.content.replace(/[#>*_`~\[\]()!-]+/g,' ').replace(/\s+/g,' ').slice(0,100)||'空白笔记'}</p><small>{notebooks.find(b=>b.id===n.notebookId)?.name??'默认'} · {new Date(n.updatedAt).toLocaleDateString()}</small></div><div className="note-row-actions" onClick={e=>e.stopPropagation()}><button className={n.active?'note-active-toggle is-active':'note-active-toggle'} onClick={()=>toggleActive(n)}>{n.active?'● 已激活':'○ 激活'}</button>{!selectedNotebook&&<><button disabled={index===0} onClick={()=>move(n.id,-1)}>↑</button><button disabled={index===shown.length-1} onClick={()=>move(n.id,1)}>↓</button></>}</div></article>):<p className="page-empty">{selectedNotebook?'这个笔记本还是空的。':'还没有已激活笔记。'}</p>}</div>
  {selectedNotebook&&<button className="notes-back" onClick={()=>setSelectedNotebook(null)}>← 返回已激活笔记</button>}
  {notebookOpen&&<div className="notes-overlay"><button className="modal-backdrop" aria-label="关闭笔记本" onClick={()=>setNotebookOpen(false)}/><aside className="notebook-drawer"><header><h3>笔记本</h3><button onClick={()=>setNotebookOpen(false)}>×</button></header>{notebooks.sort((a,b)=>a.order-b.order).map(b=><div className="notebook-row" key={b.id}><button onClick={()=>{setSelectedNotebook(b.id);setNotebookOpen(false)}}><strong>{b.name}</strong><span>{notes.filter(n=>n.notebookId===b.id&&!n.trashedAt).length}</span></button>{!b.system&&<button className="danger-quiet" onClick={()=>deleteNotebook(b)}>删除</button>}</div>)}<button className="notebook-add" onClick={addNotebook}>＋ 新建笔记本</button></aside></div>}
  {editing&&<div className="note-editor-overlay" style={editorViewportStyle}><button className="modal-backdrop" aria-label="关闭笔记" onClick={()=>setEditingId(null)}/><div className="note-editor"><header><input value={editing.title} onChange={e=>patch({title:e.target.value})}/><div><button className={editing.active?'note-active-toggle is-active':'note-active-toggle'} onClick={()=>toggleActive(editing)}>{editing.active?'● 已激活':'○ 激活'}</button><button className="danger-quiet" onClick={()=>deleteNote(editing)}>删除</button><button onClick={()=>setEditingId(null)}>完成</button></div></header><div className="note-meta"><select value={editing.notebookId} onChange={e=>patch({notebookId:e.target.value})}>{notebooks.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><span>{new Date(editing.updatedAt).toLocaleString()}</span></div><div className="note-mobile-tabs"><button className={mobileMode==='edit'?'active':''} onClick={()=>setMobileMode('edit')}>编辑</button><button className={mobileMode==='preview'?'active':''} onClick={()=>setMobileMode('preview')}>预览</button></div><div className="note-attachments"><div className="note-attachment-section"><span>图片 · 最多 9 张</span><label className="attachment-add">＋ 从设备添加<input type="file" accept="image/*" multiple onChange={event=>{void onAddImages(editing.id,event.target.files);event.currentTarget.value=''}} disabled={(editing.attachments??[]).filter(a=>a.type==='image').length>=9}/></label>{(editing.attachments??[]).some(a=>a.type==='image')&&<div className="note-attachment-grid">{(editing.attachments??[]).filter(a=>a.type==='image').map(a=><NoteImage key={a.id} attachment={a} getBlob={getAttachmentBlob} onPreview={onPreviewImage} onRemove={()=>removeAttachment(a)}/>)}</div>}<small>自动压缩后保存 · 单张约 1 MB</small></div><div className="note-attachment-section"><span>录音 · 最多 1 条 / 30 分钟</span>{(editing.attachments??[]).find(a=>a.type==='audio')?(()=>{const audio=(editing.attachments??[]).find(a=>a.type==='audio')!;return <div className="note-audio-row"><NoteAudio attachment={audio} getBlob={getAttachmentBlob}/><button type="button" onClick={()=>removeAttachment(audio)}>删除录音</button></div>})():<button type="button" className="record-button" onClick={recording?stopRecording:()=>void startRecording()}>{recording?`■ 停止录音 ${Math.floor(recordingSeconds/60)}:${String(recordingSeconds%60).padStart(2,'0')}`:'● 开始录音'}</button>}</div></div><div className={`note-split mobile-${mobileMode}`}><div className="note-edit-pane"><MarkdownEditorAdapter value={editing.content} onChange={content=>patch({content})} onScrollRatio={syncPreviewScroll}/></div><div ref={previewRef} className="note-preview-pane"><MarkdownRenderer content={editing.content}/></div></div></div></div>}
 </section>
}

function NoteImage({attachment,getBlob,onPreview,onRemove}:{attachment:Attachment;getBlob:(key:string)=>Promise<Blob|undefined>;onPreview:(attachment:Attachment)=>void;onRemove:()=>void}){const[url,setUrl]=useState('');useEffect(()=>{let active=true,objectUrl='';getBlob(attachment.storageKey).then(blob=>{if(!active||!blob)return;objectUrl=URL.createObjectURL(blob);setUrl(objectUrl)});return()=>{active=false;if(objectUrl)URL.revokeObjectURL(objectUrl)}},[attachment.storageKey,getBlob]);return <div className="note-attachment-card"><button type="button" onClick={()=>onPreview(attachment)} disabled={!url}>{url?<img src={url} alt={attachment.filename}/>:<span>加载中…</span>}</button><small title={attachment.filename}>{attachment.filename}</small><button type="button" className="note-attachment-remove" onClick={onRemove} aria-label={`删除 ${attachment.filename}`}>×</button></div>}
function NoteAudio({attachment,getBlob}:{attachment:Attachment;getBlob:(key:string)=>Promise<Blob|undefined>}){const[url,setUrl]=useState('');useEffect(()=>{let active=true,objectUrl='';getBlob(attachment.storageKey).then(blob=>{if(!active||!blob)return;objectUrl=URL.createObjectURL(blob);setUrl(objectUrl)});return()=>{active=false;if(objectUrl)URL.revokeObjectURL(objectUrl)}},[attachment.storageKey,getBlob]);return url?<audio className="journal-audio-player" controls src={url}/>:<span>录音加载中…</span>}
